export default {
  levelValue : 1,
  word: " ",
  renderWord:" ",
  points : 0,
  strike : 0,
  timeRender: 0,
  levelOne:{
    words:[
      "Uno",
      "Dos",
      "Ola",
      "Sol",
      "Que",
      "Por",
      "Rio",
      "Gato",
      "Lodo",
      "Loro",
      "Pelo",
      "Piel",
      "Cien",
      "Coral",
      "Tamal",
      "Tiara",
      "Perro",
      "Mosca",
      "Mulan",
      "Mushu",
      ],
    time: 1500
  },
  levelTwo:{
    words:[
      "Comida",
      "Tomate",
      "Cohete",
      "Lechuga",
      "Ciencia",
      "Galaxia",
      "Caminar",
      "Escapar",
      "Jupiter",
      "Teclado",
      "Saturno",
      "Cableado",
      "Pantalla",
      "Nebulosa",
      "Aventura",
      "Mercurio",
      "Estupendo",
      "Estornudo",
      "Asombroso",
      "Asteroide",
      "Pluralidad",
    ],
    time: 1000
  },
  levelThree:{
    words:[
      "Big bang",
      "Via lactea",
      "Falcon heavy",
      "Cielo pequeño",
      "Nube rasposa",
      "Agua seca",
      "Arbol dormido",
      "Rueda cuadrada",
      "Persona liquida",
      "Roca suave",
      "Madera azul",
      "Libro quemado",
      "Estante vacio",
      "Arte invisible",
      "Espejo oscuro",
      "Gota gigante",
      "Muro aireado",
      "Grito silencioso",
      "Ruido relajante",
      "Caida placentera",
      "Clara oscuridad"
    ],
    time: 900
  }
}